site_name: WIKI-Maximsu_OS
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Light Mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
plugins:
  - search
  - roamlinks
docs_dir: wiki
